#! /bin/bash

function yesterworkday() 
{ 
    if [[ "Mon" == "$(date +%a)" ]]
    then 
        echo "last friday"
    else
        echo "yesterday"
    fi
}

git log --since="$(yesterworkday)" --pretty=format:'%C(yellow)%h%Creset - %C(green)%an%Creset -%d%Creset %s %Cblue(%cr)' --committer='Pierre-Jean'
